steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "VITE_MAPS_API_KEY=$_VITE_MAPS_API_KEY",
        "-t",
        "$_IMAGE",
        ".",
      ]
images: ["$_IMAGE"]
options:
  logging: CLOUD_LOGGING_ONLY
