services:
  server:
    build: 
      context: .
      args:  
        VITE_MAPS_API_KEY: ${VITE_MAPS_API_KEY}
    restart: on-failure:3
    ports:
      - "0.0.0.0:5000:5000/tcp"
    volumes:
    - ${AWS_CREDENTIALS_PATH}:/root/.aws 
    environment:
      VITE_MAPS_API_KEY: ${VITE_MAPS_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
